version: "3.9"

services:
  nextjs:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: agritrade_app
    ports:
      - "3070:3000"
    environment:
      NODE_ENV: production
      # Add other production env variables here, e.g.:
      # DATABASE_URL: your_database_url
      # API_KEY: your_api_key
    command: pnpm run start
    restart: unless-stopped
